"""The provider marks the app draws are current with their pinned sources.

``app/Sources/JRBarUI/ProviderLogoData.swift`` is generated by
``scripts/gen_provider_logos.py``. These checks need no CoreGraphics, so
they run in ``make fast`` on any runner: the file's two digests match the
recipes and the shipped strings, and every shipped path parses to a
non-empty mark inside the 1000-unit square.
"""

from __future__ import annotations

import importlib
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]


def _generator():
    return importlib.import_module("scripts.gen_provider_logos")


def test_generated_logo_data_is_current() -> None:
    generator = _generator()
    text = generator.OUTPUT.read_text(encoding="utf-8")

    assert generator.check(generator.marks(), text) == []
    assert generator.main(["--check"]) == 0


def test_every_provider_the_app_names_has_a_mark() -> None:
    generator = _generator()
    paths, _ = generator.read_generated(generator.OUTPUT.read_text(encoding="utf-8"))

    # The marks ProviderStyle's table points at, and JR-Bar's own.
    for mark in ("claude", "openai", "gemini", "pi", "grok", "devin", "opencode", "openclaw",
                 "antigravity", "cursor", "hermes", "kiro", "t3code", "jrbar"):
        assert mark in paths, mark


def test_a_hand_edit_or_a_moved_source_is_caught(tmp_path: Path) -> None:
    generator = _generator()
    text = generator.OUTPUT.read_text(encoding="utf-8")
    table = generator.marks()

    edited = text.replace('"pi": "M', '"pi": "M1 1L2 2ZM', 1)
    assert "the path strings were edited by hand" in generator.check(table, edited)

    moved = [*table[:-1], generator.Mark("jrbar", "JR-Bar", generator.JRBAR, (), table[0].layers, 1.0)]
    assert "the sources or the table changed since the file was generated" in generator.check(moved, text)

    stale = tmp_path / "ProviderLogoData.swift"
    stale.write_text(edited, encoding="utf-8")
    assert generator.main(["--check", "--output", str(stale)]) == 1


@pytest.mark.parametrize("data", ["7 7", "M1", "M1 2Z3", "Mx 1", "M0 0A1 1 0 2 0 1 1", "M0 0Q1"])
def test_the_path_parser_rejects_bad_data(data: str) -> None:
    generator = _generator()

    with pytest.raises(generator.PathError):
        generator.parse_path(data)
